"""add_user_api_keys

Revision ID: 0c2be937f077
Revises: a1b2c3d4e5f6
Create Date: 2026-02-03 08:30:42.875117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c2be937f077'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agentconfig_category', table_name='agentconfig')
    op.drop_constraint('fk_agentconfig_parent_config_id', 'agentconfig', type_='foreignkey')
    op.create_foreign_key(None, 'agentconfig', 'agentconfig', ['parent_config_id'], ['id'])
    op.alter_column('agenttypemetadata', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('agenttypemetadata', 'default_system_prompt',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint('agenttypemetadata_created_by_fkey', 'agenttypemetadata', type_='foreignkey')
    op.create_foreign_key(None, 'agenttypemetadata', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agenttypemetadata', type_='foreignkey')
    op.create_foreign_key('agenttypemetadata_created_by_fkey', 'agenttypemetadata', 'user', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('agenttypemetadata', 'default_system_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('agenttypemetadata', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'agentconfig', type_='foreignkey')
    op.create_foreign_key('fk_agentconfig_parent_config_id', 'agentconfig', 'agentconfig', ['parent_config_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_agentconfig_category', 'agentconfig', ['category'], unique=False)
    # ### end Alembic commands ###
