"""add advanced agent config

Revision ID: 35554ac50164
Revises: acd0deed997c
Create Date: 2026-01-09 22:04:47.047604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35554ac50164'
down_revision: Union[str, None] = 'acd0deed997c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentconfig', sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agentconfig', sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agentconfig', sa.Column('context_window', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentconfig', 'context_window')
    op.drop_column('agentconfig', 'schedule_config')
    op.drop_column('agentconfig', 'trigger_config')
    # ### end Alembic commands ###
