"""sync_db_and_fixes

Revision ID: 4713ab19adcc
Revises: e52891234567
Create Date: 2026-01-09 10:52:40.177101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4713ab19adcc"
down_revision: Union[str, None] = "e52891234567"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_message_created_at"), "message", ["created_at"], unique=False)
    op.create_index(op.f("ix_message_room_id"), "message", ["room_id"], unique=False)
    # op.drop_constraint(op.f("user_full_name_key"), "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("user_full_name_key"), "user", ["full_name"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_message_room_id"), table_name="message")
    op.drop_index(op.f("ix_message_created_at"), table_name="message")
    # ### end Alembic commands ###
