"""Refactor Agent Management (Phases 1-3)

Revision ID: 49388994d55d
Revises: 67a4c87e67e1
Create Date: 2026-02-20 19:59:46.552749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49388994d55d'
down_revision: Union[str, None] = '67a4c87e67e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a2a_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('room_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_a2a_messages_correlation_id'), 'a2a_messages', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_a2a_messages_message_id'), 'a2a_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_a2a_messages_room_id'), 'a2a_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_a2a_messages_sender_id'), 'a2a_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_a2a_messages_type'), 'a2a_messages', ['type'], unique=False)
    op.create_table('organization',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_table('user_api_key',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('encrypted_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_key_alias'), 'user_api_key', ['alias'], unique=False)
    op.create_index(op.f('ix_user_api_key_provider'), 'user_api_key', ['provider'], unique=False)
    op.create_index(op.f('ix_user_api_key_user_id'), 'user_api_key', ['user_id'], unique=False)
    op.create_table('analyticsreport',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('course_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('room_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyticsreport_course_id'), 'analyticsreport', ['course_id'], unique=False)
    op.create_index(op.f('ix_analyticsreport_room_id'), 'analyticsreport', ['room_id'], unique=False)
    op.create_table('project',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_index(op.f('ix_project_organization_id'), 'project', ['organization_id'], unique=False)
    op.create_table('userorganizationlink',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.create_table('userprojectlink',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('userroomlink',
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('room_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'room_id')
    )
    op.create_table('agent_key',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('agent_config_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('key_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agentconfig.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_key_agent_config_id'), 'agent_key', ['agent_config_id'], unique=False)
    op.create_index(op.f('ix_agent_key_key_type'), 'agent_key', ['key_type'], unique=False)
    op.create_table('agentconfigversion',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('config_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('version_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['agentconfig.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentconfigversion_config_id'), 'agentconfigversion', ['config_id'], unique=False)
    op.create_table('agentthread',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agentconfig.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentthread_agent_id'), 'agentthread', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agentthread_project_id'), 'agentthread', ['project_id'], unique=False)
    op.create_index(op.f('ix_agentthread_user_id'), 'agentthread', ['user_id'], unique=False)
    op.create_table('roomagentlink',
    sa.Column('room_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agentconfig.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'agent_id')
    )
    op.create_table('threadmessage',
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['agentthread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threadmessage_thread_id'), 'threadmessage', ['thread_id'], unique=False)
    op.add_column('agentconfig', sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_agentconfig_project_id'), 'agentconfig', ['project_id'], unique=False)
    op.drop_constraint('agentconfig_course_id_fkey', 'agentconfig', type_='foreignkey')
    op.create_foreign_key(None, 'agentconfig', 'project', ['project_id'], ['id'])
    op.drop_column('agentconfig', 'course_id')
    op.add_column('room', sa.Column('is_analytics_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_column('user', 'username')
    op.drop_column('room', 'is_analytics_active')
    op.add_column('agentconfig', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agentconfig', type_='foreignkey')
    op.create_foreign_key('agentconfig_course_id_fkey', 'agentconfig', 'course', ['course_id'], ['id'])
    op.drop_index(op.f('ix_agentconfig_project_id'), table_name='agentconfig')
    op.drop_column('agentconfig', 'project_id')
    op.drop_index(op.f('ix_threadmessage_thread_id'), table_name='threadmessage')
    op.drop_table('threadmessage')
    op.drop_table('roomagentlink')
    op.drop_index(op.f('ix_agentthread_user_id'), table_name='agentthread')
    op.drop_index(op.f('ix_agentthread_project_id'), table_name='agentthread')
    op.drop_index(op.f('ix_agentthread_agent_id'), table_name='agentthread')
    op.drop_table('agentthread')
    op.drop_index(op.f('ix_agentconfigversion_config_id'), table_name='agentconfigversion')
    op.drop_table('agentconfigversion')
    op.drop_index(op.f('ix_agent_key_key_type'), table_name='agent_key')
    op.drop_index(op.f('ix_agent_key_agent_config_id'), table_name='agent_key')
    op.drop_table('agent_key')
    op.drop_table('userroomlink')
    op.drop_table('userprojectlink')
    op.drop_table('userorganizationlink')
    op.drop_index(op.f('ix_project_organization_id'), table_name='project')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_analyticsreport_room_id'), table_name='analyticsreport')
    op.drop_index(op.f('ix_analyticsreport_course_id'), table_name='analyticsreport')
    op.drop_table('analyticsreport')
    op.drop_index(op.f('ix_user_api_key_user_id'), table_name='user_api_key')
    op.drop_index(op.f('ix_user_api_key_provider'), table_name='user_api_key')
    op.drop_index(op.f('ix_user_api_key_alias'), table_name='user_api_key')
    op.drop_table('user_api_key')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_a2a_messages_type'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_sender_id'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_room_id'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_message_id'), table_name='a2a_messages')
    op.drop_index(op.f('ix_a2a_messages_correlation_id'), table_name='a2a_messages')
    op.drop_table('a2a_messages')
    # ### end Alembic commands ###
