"""add_artifact_table

Revision ID: 67a4c87e67e1
Revises: d7681c7a7d4f
Create Date: 2026-02-08 17:22:01.456728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a4c87e67e1'
down_revision: Union[str, None] = 'd7681c7a7d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact',
    sa.Column('room_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_artifact_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('last_modified_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifact_parent_artifact_id'), 'artifact', ['parent_artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_room_id'), 'artifact', ['room_id'], unique=False)
    op.create_index(op.f('ix_artifact_type'), 'artifact', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_type'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_room_id'), table_name='artifact')
    op.drop_index(op.f('ix_artifact_parent_artifact_id'), table_name='artifact')
    op.drop_table('artifact')
    # ### end Alembic commands ###
