"""remove legacy fields from agent_room_state

Revision ID: 817324835f6c
Revises: 72a8dfafc74a
Create Date: 2026-02-24 15:54:53.495227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '817324835f6c'
down_revision: Union[str, None] = '72a8dfafc74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_room_state', 'message_count_since_last_reply')
    op.drop_column('agent_room_state', 'monologue_count')
    op.drop_column('agent_room_state', 'is_sleeping')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_room_state', sa.Column('is_sleeping', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('agent_room_state', sa.Column('monologue_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('agent_room_state', sa.Column('message_count_since_last_reply', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
