"""Add model column

Revision ID: acd0deed997c
Revises: ca87a764f29b
Create Date: 2026-01-09 20:32:05.313542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'acd0deed997c'
down_revision: Union[str, None] = 'ca87a764f29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentconfig', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agentconfig', 'model')
    # ### end Alembic commands ###
