"""add_brain_profiles

Revision ID: ca87a764f29b
Revises: 4713ab19adcc
Create Date: 2026-01-09 16:18:12.448363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca87a764f29b'
down_revision: Union[str, None] = '4713ab19adcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agentconfig', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('agentconfig', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('agentconfig', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'agentconfig', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agentconfig', type_='foreignkey')
    op.drop_column('agentconfig', 'created_by')
    op.drop_column('agentconfig', 'is_active')
    op.drop_column('agentconfig', 'name')
    # ### end Alembic commands ###
